[package]
name = "roost"
description = "Command line interpreter for the roost language"
version = "1.1.0"
edition = "2021"
authors = ["RubixDev"]
license = "GPL-2.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = { version = "1.20.0", features = ["maths"] }
structopt = "0.3.26"
